---
language: c
sudo: false
env:
  global:
  - RACKET_DIR=~/racket
  matrix:
  - RACKET_VERSION=6.3 RACKET_MINIMAL=1
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cd travis-racket
  - git checkout minimal
  - cd ..
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
install:
before_script:
script:
  - "./bin/check-exercises.sh"
  - "./bin/fetch-configlet"
  - "./bin/configlet ."
after_script:
